---

- name: Download grafana deb package
  ansible.builtin.get_url:
    url:  https://dl.grafana.com/oss/release/grafana_9.3.6_amd64.deb
    dest: /tmp/grafana_9.3.6_amd64.deb
    
- name: Install a .deb package
  ansible.builtin.apt:
    deb: /tmp/grafana_9.3.6_amd64.deb

- name: systemctl enable grafana
  command:  systemctl enable grafana-server

- name: systemctl start grafana
  command:  systemctl start grafana-server  

- name: show  status
  shell: 'systemctl status grafana-server '
  register: command_output

- debug: 
    var: command_output.stdout_lines


- name: show  port 9090 
  shell: 'netstat -tulapn '
  register: command_output

- debug: 
    var: command_output.stdout_lines    