filebeat.inputs:
- type: log
  id: test-postgres
  enabled: true
  paths:
    - /var/log/postgresql/postgresql-12-main.log

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml

  reload.enabled: true

setup.template.settings:
  index.number_of_shards: 1


setup.kibana:

output.logstash:
  hosts: ["10.0.9.178:5044"]

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

